//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAYQuiltProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOM
    {
        public int BomId { get; set; }
        public string TypeOfItem { get; set; }
        public string Count { get; set; }
        public string Description { get; set; }
        public int QuiltQuiltId { get; set; }
    
        public virtual Quilt Quilt { get; set; }
    }
}
