//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAYQuiltProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderHistory
    {
        public int OrderHistoryId { get; set; }
        public string Phase { get; set; }
        public string BeginDate { get; set; }
        public string EndDate { get; set; }
        public string Comments { get; set; }
        public int OrderOrderId { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
