//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAYQuiltProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QulltContext : DbContext
    {
        public QulltContext()
            : base("name=QulltContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Order> Orders { get; set; }
        public DbSet<Quilt> Quilts { get; set; }
        public DbSet<Recipient> Recipients { get; set; }
        public DbSet<OrderHistory> OrderHistories { get; set; }
        public DbSet<DesignBlock> DesignBlocks { get; set; }
        public DbSet<BOM> BOMs { get; set; }
        public DbSet<Award> Awards { get; set; }
    }
}
