//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAYQuiltProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quilt
    {
        public Quilt()
        {
            this.BOMs = new HashSet<BOM>();
            this.Awards = new HashSet<Award>();
        }
    
        public int QuiltId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual DesignBlock DesignBlock { get; set; }
        public virtual ICollection<BOM> BOMs { get; set; }
        public virtual ICollection<Award> Awards { get; set; }
    }
}
